### ISSUE TITLE
Example using Portals or alternative triggers/targets

### ISSUE THREAD

**Issue by JackEdwardLyons** [accessible-ui/drawer#5]
Hi there,

Do you have any live examples on how to use the drawer component with portals or custom triggers / targets?
I'm trying to hook up a custom drawer to open on button click but not sure exactly how to do it. Here is a sandbox link: https://codesandbox.io/s/accessibledrawer-example-forked-b52l3?file=/src/index.js

Thank you in advance

**Comment by jaredLunde** [comment]
There's a lot going on here but I'll do my best:

1. The `portal` prop expects you to have a `<div id='portals'/>` element in your app if the value is `true`. You can also provide a custom selector here e.g. `<Target portal='#foo'>`. From the docs:
> When true this will render the drawer into a React portal with the id #portals. You can render it into any portal by providing its query selector here, e.g. #foobar, [data-portal=true], or .foobar.
2. You put the `portal` prop on the `<Drawer>` instead of `<Target>`
3. You're using `useA11yTrigger()` outside of the `<Drawer>` context provider. Every hook and component must be declared inside of `<Drawer>`.

Perhaps the docs should be better at illustrating some of the above. Nothing can happen outside of `<Drawer>`.

**Comment by JackEdwardLyons** [comment]
Ah I see, so no matter what, the elements needs to be wrapped in a `<Drawer>`. That wasn't clear to me.

Thanks for the help.
